### ISSUE TITLE
Sync Strategies

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-sdk#2]
Some questions/tips regarding the `Sync Strategies` document:

> ### Hitting Sync
> - ``OCCore`` first processes the Sync Records in the Sync Journal
> - ``OCCore`` then requests current information for all *Available Offline* items, compares it against > its cached information
>  - if there are no conflicts with remaining Sync Records: mirror changes locally
>  - if there are conflicts with remaining Sync Records: do not make changes locally
> What does "all information" means? list of information/database with locally-browsed files/folders? I > guess it has to be updated each time the server is requested 

not sure about the part of conflicts. If user performs two "conflicting" actions over an available offline item (in Av. offline list, stored in `OCCore`), your solution is not making changes locally, afaiu. For example, if the item is an available offline text file, and i change twice the same line locally, which should be the behaviour? guessing that all the core info is already cached.

> ### Delete (triggered locally by user)
> ...
> - **Item changed on the server**: Warn the user and ask for confirmation (changes suggest the user > may want to keep the item). Include last modified date of the server item and timestamp of the action.

If the user wants to remove a file/folder locally, i agree that a confirmation should be asked to protect the destructive action. But this confirmation should be asked always, no matter if the file/folder has a new version or not in server side. Actions have a temporal line. File updated first (server), and then file deleted (in client)... maybe we can guess that the user does not want the file anymore. Open to discussion.

> ### Delete (triggered by sync with remote)
> - ...
> - **Item changed locally**: Warn the user and ask for confirmation (changes suggest the user may > > want to keep the item). Include last modified date of the local item and offer to upload it again (=> 
> creates Upload Sync Record).

In this case the user tries to modify an item that does not exist in server side. I mean that this scenario should be avoided. 

> ### Create Directory
> - **Item with same name and path exists on server**:
>  - existing item is a directory: do nothing.
>  - existing item is a file: Inform user and remove Sync Record.

if the user tries to create a folder with an already existing name, it should be notified to the user, no matter if the item is a file or folder. The desired action is not performed and the user should know why, imho.

@michaelstingl @nasli @pablocarmu @felix-schwarz

**Comment by felix-schwarz** [comment]
> not sure about the part of conflicts. If user performs two "conflicting" actions over an available offline item (in Av. offline list, stored in `OCCore`), your solution is not making changes locally, afaiu. For example, if the item is an available offline text file, and i change twice the same line locally, which should be the behaviour? guessing that all the core info is already cached.

This is what would happen in that case:
1) User hits Available Offline: OCCore downloads a copy of the server version to Offline Storage. At this point, the cache information is identical to that on the server.

2) User goes offline, makes 1st edit: OCCore looks for existing Sync Record for this file, which it does not find. OCCore then creates a new Sync Record for this file, which includes a (serialized/archived) copy of the OCItem as found in the cache (ArchCopy). The edited version 1 of the text file overwrites the previous version in Offline Storage.

3) User still offline, makes 2nd edit: OCCore looks for existing Sync Record, which it finds. It keeps the ArchCopy of that record and then replaces it. The edited version 2 of the text file overwrites edited version 1 in Offline Storage.

4) User is back online, sync starts: OCCore runs through all Sync Records. For the edited text file: OCCore asks the server for current info on the text file. If that info matches the ArchCopy data previously stored in the Sync Record, it uploads the changed file.

> > ### Delete (triggered locally by user)
> > ...
> > - **Item changed on the server**: Warn the user and ask for confirmation (changes suggest the user > may want to keep the item). Include last modified date of the server item and timestamp of the action.
> 
> If the user wants to remove a file/folder locally, i agree that a confirmation should be asked to protect the destructive action. But this confirmation should be asked always, no matter if the file/folder has a new version or not in server side. 

The Sync Strategies document only covers what should take place while the sync process is running, not general UI (where I agree, users should always be asked for confirmation on destructive actions). Sorry if this isn't clear from the document. I'll add language to it accordingly.

> Actions have a temporal line. File updated first (server), and then file deleted (in client)... maybe we can guess that the user does not want the file anymore. Open to discussion.

I think guessing would be fine in a single user scenario. But it could go really wrong in a multi-user environment. Example:

1. A (offline) has version 1 of a document Available Offline on his iPhone.
2. B works on version 2 of the document and saves it to the server.
3. A (still offline) runs out of space on his iPhone and thinks "I no longer need this" and deletes version 1.
4. A comes back online and starts syncing with the server…

A had the intention to delete version 1, but didn't have the intention to delete B's work. Therefore, I'd always ask the user to decide what to do in such cases and not rely solely on the event timeline.

> > ### Delete (triggered by sync with remote)
> > - ...
> > - **Item changed locally**: Warn the user and ask for confirmation (changes suggest the user may > > want to keep the item). Include last modified date of the local item and offer to upload it again (=> 
> > creates Upload Sync Record).
> 
> In this case the user tries to modify an item that does not exist in server side. I mean that this scenario should be avoided. 
>

Unfortunately, I don't think it can be avoided. I had a scenario like this in mind:
1. A (online) choses to make a document Available Offline
2. A subsequently goes offline
3. A (offline) edits the file
4. B deletes the file on the server
5. A comes back online and starts syncing with the server…

I think in such a case the user should be given a chance to keep their work.

> > ### Create Directory
> > - **Item with same name and path exists on server**:
> >  - existing item is a directory: do nothing.
> >  - existing item is a file: Inform user and remove Sync Record.
> 
> if the user tries to create a folder with an already existing name, it should be notified to the user, no matter if the item is a file or folder.

I had a scenario like this in mind:
1. A (offline) creates new folder N
2. B (online) creates new folder N
3. A (offline) adds a file to folder N
4. A comes back online and starts syncing with the server…

As a user, I would expect not to be notified that folder N has already been created at step 4, since there really is no conflict.

On the other hand: if B f.ex. copied a complete tree of header files into folder N at step 2. And A copied a different tree of headers into folder N at step 3, automatically syncing the two would result in a mix of the two different sets of headers, which is highly likely not what the users wanted.

Maybe giving the user the choice to "Merge", "Rename" and "Rename as '[Name] [RunningNumber]'" would be better there.

What do you think?

> The desired action is not performed and the user should know why, imho.

The user is informed in case a file with that name already exists, as a folder and file by the same name can't exist in the same place.

However, I just noticed that "Inform user and remove Sync Record" is not the right approach here, either. Instead, it should really be "Inform user, prompt user for a different name (and offer a quick choice like '[Name] [RunningNumber]'.".

What do you think?

@michaelstingl @nasli @pablocarmu @jesmrec

**Comment by jesmrec** [comment]
One of the (important) considerations you have is that the app/sdk will work in offline mode, so when connectivity is restablished, all operations performed in offline will be pushed to the server. Really, this consideration answer many of my questions.

> On the other hand: if B f.ex. copied a complete tree of header files into folder N at step 2. And A >copied a different tree of headers into folder N at step 3, automatically syncing the two would result >in a mix of the two different sets of headers, which is highly likely not what the users wanted.

>Maybe giving the user the choice to "Merge", "Rename" and "Rename as '[Name] [RunningNumber]'" >would be better there.

>What do you think?

Such scenario would only happen within a shared folder (there is no other way for two users to upload content to the same folder, at least in the current app). In this case, if both users upload content with same headers (conflicts happen), merging will make this folder a mess. Renaming (with or without a running number) is a better solution, i mean.

> However, I just noticed that "Inform user and remove Sync Record" is not the right approach here, 
> either. Instead, it should really be "Inform user, prompt user for a different name (and offer a quick >choice like '[Name] [RunningNumber]'

Agreed.

**Comment by jesmrec** [comment]
Other question syncing-related: You will keep in the SDK a cached copy of the server:

> OCCore keeps a cache of all information it received from the server in its OCDatabase

how often will the server info be requested to keep the local copy updated? or the strategy to retrieve info from remote by optimizing data plan/battery use.

Thanks again for your effort

**Comment by felix-schwarz** [comment]
> how often will the server info be requested to keep the local copy updated? or the strategy to retrieve info from remote by optimizing data plan/battery use.

The cache is updated by OCCore whenever it gets new data, i.e. following a OCQuery being started by the app, or sync being started by the app.

The frequency with which Available Offline folders are queried for changes will be determined by the app using the SDK, not the SDK itself.

The app could trigger sync f.ex. whenever it comes to the foreground, the user triggers sync or the last sync is longer than [timespan] ago.

**Comment by jesmrec** [comment]
The update of the document is OK from my side, after checking it.

> The cache is updated by OCCore whenever it gets new data, i.e. following a OCQuery being started 
> by the app, or sync being started by the app.

ok, we will deal with this in the scope of the app. A good balance between sync' / battery / data usage is crucial.

>The frequency with which Available Offline folders are queried for changes will be determined by the >app using the SDK, not the SDK itself.

same for this

**Comment by jesmrec** [comment]
I will put other topic related: Server capabilities. Also to be stored and synced in Core with the values of server side.
